AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 15
    Runtime: nodejs12.x
    Environment:
      Variables:
        TABLE_NAME: !Ref CurrencyTable

Resources:

  UpdateConfigFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/put-config
      Handler: put-config.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource: !GetAtt CurrencyTable.Arn
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /config
            Method: put

  GetCurrenciesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-currencies
      Handler: get-currencies.handler
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:GetItem
              Resource: !GetAtt CurrencyTable.Arn
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /currencies
            Method: get

  CurrencyTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
        - AttributeName: userId
          AttributeType: S
      KeySchema: 
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiUrl:
    Description: "API URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
